// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5474.SullyGoesToRobotBuilder2018;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static DigitalInput displayLimitSwitchSettingLimitSwitchManual;
    public static AnalogInput driveUltraSonic;
    public static SpeedController driveleftmotor;
    public static SpeedController driverightmotor;
    public static RobotDrive driveRobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        displayLimitSwitchSettingLimitSwitchManual = new DigitalInput(0);
        LiveWindow.addSensor("DisplayLimitSwitchSetting", "Limit Switch Manual", displayLimitSwitchSettingLimitSwitchManual);
        
        driveUltraSonic = new AnalogInput(1);
        LiveWindow.addSensor("Drive", "UltraSonic", driveUltraSonic);
        
        driveleftmotor = new Spark(8);
        LiveWindow.addActuator("Drive", "left motor", (Spark) driveleftmotor);
        driveleftmotor.setInverted(false);
        driverightmotor = new Spark(9);
        LiveWindow.addActuator("Drive", "right motor", (Spark) driverightmotor);
        driverightmotor.setInverted(false);
        driveRobotDrive = new RobotDrive(driveleftmotor, driverightmotor);
        
        driveRobotDrive.setSafetyEnabled(true);
        driveRobotDrive.setExpiration(0.1);
        driveRobotDrive.setSensitivity(0.5);
        driveRobotDrive.setMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
